# Generated by Django 4.2.18 on 2025-11-03 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project_first_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="owners",
            field=models.ManyToManyField(
                related_name="cars",
                through="project_first_app.Ownership",
                to="project_first_app.owner",
            ),
        ),
        migrations.AlterField(
            model_name="driverlicense",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="licenses",
                to="project_first_app.owner",
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="date_end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ownership",
            name="date_start",
            field=models.DateField(),
        ),
    ]
