site_name: Lab1 Docs
site_description: Документация к лабораторной работе 1

theme:
  name: mkdocs
  palette:
    primary: blue
    accent: light blue

nav:
  - Home: index.md


markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite